# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ v2.7 ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose

      - name: Compile Python
        run: |
          curl -O -L -s https://github.com/python/cpython/archive/2.7.tar.gz
          ls
          tar xf v2.7.tar.gz
          ls
          cd cpython-2.7
          ls
          PCbuild\build.bat -e -p x64
          PCbuild\build.bat -e -p ARM64
      - name: Create zip file
        shell: cmd
        run: |
          mkdir cpython-2.7\PCBuild\arm64\lib
          mkdir cpython-2.7\PCBuild\arm64\include
          xcopy /i /e cpython-2.7\lib\*.* cpython-2.7\PCBuild\arm64\lib
          xcopy /i /e cpython-2.7\include\*.* cpython-2.7\PCBuild\arm64\include
          powershell Compress-7Zip "cpython-2.7\PCBuild\arm64" -ArchiveFileName "Python-2.7-Windows-ARM64.zip" -Format Zip
      - name: Building EXE and ZIP
        shell: cmd
        run: |
          cd cpython-2.7
          call "PCbuild\find_msbuild.bat" %MSBUILD%
          mkdir Tools\nuget\PCbuild
          xcopy /i /e PCbuild\*.* Tools\nuget\PCbuild\
          set PCBUILD=PCbuild\
          mkdir externals
          set EXTERNALS=externals
          set Py_OutDir=%PCBUILD%
          call "Tools\msi\get_externals.bat"
          dir externals
          set RELEASE_URI=http://github.com/jay0lee/CPython-Windows-{arch}
          set DOWNLOAD_URL=$RELEASE_URI/releases
          mkdir nuget_out
          set BUILDOPTS=/p:Platform=arm64 /p:BuildForRelease=true /p:DownloadUrl=%DOWNLOAD_URL% /p:DownloadUrlBase= /p:ReleaseUri=%RELEASE_URI%
          %MSBUILD% Tools\msi\bundle\releaselocal.wixproj /t:Rebuild %BUILDOPTS% /p:RebuildAll=true
          dir PCBuild
          dir nuget_out
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated Release by GitHub Action CI
          draft: true
          prerelease: false

      - name: Upload GitHub Release File
        id: upload-release-asset-arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Python-2.7-Windows-ARM64.zip
          asset_name: Python-2.7-Windows-ARM64.zip
          asset_content_type: application/zip
